included:
  - Tests
  #- Sources

disabled_rules:
  - line_length
  - force_cast
  - trailing_whitespace

opt_in_rules:
   - empty_count
   #- missing_docs

type_body_length:
  - 1000 # warning
  - 1500 # error
