
language: objective-c
osx_image: xcode8

before_install:
  - gem install xcpretty -N --no-ri --no-rdoc

script:
  - swift -version
  - xcodebuild -version
  - xcodebuild -showsdks
  - sleep 5
  - set -o pipefail
  - xcodebuild clean build -project BFKit.xcodeproj -scheme BFKit -destination "platform=iOS Simulator,name=iPhone 7 Plus" -enableCodeCoverage YES | xcpretty
