os:
  - linux
  - osx
language: generic
sudo: required
dist: trusty
osx_image: xcode8.2

before_install:
  - if [ "$TRAVIS_OS_NAME" == "osx" ]; then
      gem install xcpretty -N --no-ri --no-rdoc;
      gem install cocoapods --pre --no-rdoc --no-ri --no-document;
      brew update;
      brew outdated carthage || brew upgrade carthage;
      SIMULATOR_ID=$(xcrun instruments -s | grep -o "iPhone 7 Plus (10.2) \[.*\]" | grep -o "\[.*\]" | sed "s/^\[\(.*\)\]$/\1/");
    fi

install:
  - if [ "$TRAVIS_OS_NAME" == "linux" ]; then
      eval "$(curl -sL https://gist.githubusercontent.com/kylef/5c0475ff02b7c7671d2a/raw/02090c7ede5a637b76e6df1710e83cd0bbe7dcdf/swiftenv-install.sh)";
    fi
  - if [ "$TRAVIS_OS_NAME" == "osx" ]; then
      ./install_swiftlint.sh;
    fi

script:
  - if [ "$TRAVIS_OS_NAME" == "linux" ]; then
        swiftenv version;
    fi
  - if [ "$TRAVIS_OS_NAME" == "osx" ]; then
      swift -version
      xcodebuild -version;
      xcodebuild -showsdks;
      swiftlint;
      sleep 5;
      set -o pipefail;
      echo $SIMULATOR_ID;
      open -a "Simulator" --args -CurrentDeviceUDID $SIMULATOR_ID
      xcodebuild clean test -project BFKit.xcodeproj -scheme BFKit -enableCodeCoverage YES | xcpretty;
      xcodebuild -project Example/BFKitExample.xcodeproj -scheme BFKitExample -configuration Debug ONLY_ACTIVE_ARCH=NO build | xcpretty;
      pod lib lint --verbose;
      carthage build --no-skip-current;
    fi
  - if [ "$TRAVIS_OS_NAME" == "linux" ]; then
      swift build;
      swift test;
    fi

after_success:
  - if [ "$TRAVIS_OS_NAME" == "osx" ]; then
      bash <(curl -s https://codecov.io/bash);
      sleep 5;
    fi
